export const SEARCH_REPOSITORIES_SUCCESS = "SEARCH_REPOSITORIES_SUCCESS";
export const REMOVE_CARD_SUCCESS = "REMOVE_CARD_SUCCESS";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const LOAD_REPOSITORY_SUCCESS = "LOAD_REPOSITORY_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";